name: weather_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.10.6'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # CORE
  async_task: ^1.1.1
  flutter_gen: ^5.4.0
  collection: ^1.18.0
  easy_localization: ^3.0.4
  easy_logger: ^0.0.2
  freezed_annotation: ^2.4.1
  go_router: ^13.2.0
  logger: ^2.0.2+1
  talker: ^4.0.1
  talker_dio_logger: ^4.0.1
  talker_flutter: ^4.0.1
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  flutter_flavor: ^3.1.3
  geolocator: 10.1.1
  country_list_pick: ^1.0.1+6
  dart_date: ^1.2.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  hive: 4.0.0-dev.2
  isar_flutter_libs: ^4.0.0-dev.13

  # NETWORK & DATA
  dio: ^5.4.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

  # UI
  flutter_keyboard_visibility: ^6.0.0
  reactive_forms: ^16.1.1
  flash: ^3.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  build: ^2.4.1
  build_runner: ^2.4.8
  build_verify: ^3.1.0
  build_resolvers: ^2.4.2
  flutter_gen_runner: ^5.4.0
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.11
  freezed: ^2.4.7
  go_router_builder: ^2.4.1

flutter:
  generate: false
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/images/


  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu/Ubuntu-Medium.ttf
          weight: 500

    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500

flutter_gen:
  output: lib/generated/
  line_length: 100

  integrations:
    flutter_svg: true
    flare_flutter: true

  colors:
    inputs:
      - assets/colors/colors.xml